/**
 * Created by WB on 2017/8/22.
 */
export const BOTTOM_SHOW_HANDLE = 'BOTTOM_SHOW_HANDLE'
export const BUTTOM_HIDE_HANDLE = 'BUTTOM_HIDE_HANDLE'
export const CURRENT_ROUTER = 'CURRENT_ROUTER'
export const ALERT_SHOW = 'ALERT_SHOW'
